### ISSUE TITLE
Please Halp

### ISSUE THREAD

**Issue by Th3-Think3r** [itsmehacker/DarkScrape#2]
<img width="575" alt="DarkScrape" src="https://user-images.githubusercontent.com/49915827/60980045-5a79d100-a2f9-11e9-92bb-4ab5f5de8b0e.PNG">

**Comment by Vause** [comment]
I believe `os` and `csv` are part of python's standard library. Remove them from the requirements.txt document and try running `pip3 install -r requirements.txt` again

**Comment by itsmehacker** [comment]
please git pull once script has been updated

**Comment by Th3-Think3r** [comment]
@Vause 

Thanks, that worked perfectly.
