### ISSUE TITLE
Cannot start

### ISSUE THREAD

**Issue by giovanniabramo** [itsmehacker/DarkScrape#3]
Good evening. I have already opened tor browser, but I get this error.
![image](https://user-images.githubusercontent.com/48349809/61059862-6ef5c080-a402-11e9-9d0b-24115a2b4c4c.png)

**Comment by itsmehacker** [comment]
@giovanniabramo 

Tor Browser is a Browser not a service 

if you are using Kali linux 
apt-get install tor
service start tor
for Arch Linux 
pacman -S tor 
systemctl start tor 
After That rerun the script it will work fine

**Comment by itsmehacker** [comment]
Closing Due to Inactive
